# Site settings
name: "mb21â€™s blog"
description: "about society, philosophy, design, movies, tech, etc."
url: "http://mb21.github.io/blog"
githubUsername: mb21
twitterUsername: mb2100

# Build settings
# markdown: kramdown
permalinks: pretty

# Plugins
pandoc:
  skip: false
  impose: false
  output: ./tmp
  flags:
  site_flags:
  outputs:
    html:
